feat: adicionado header com modal logout de sessão e useAuth para man…
afonsocardz/projeto17-linkr-front pull request #5
Opened 2022-08-12 01:41 UTC by carlosandretaiga

…ter logado entre refreshes.

2022-08-12 11:35 UTC, GabrielaTiago approved these changes

2022-08-13 15:41 UTC, carlosandretaiga commented
@afonsocardz poderia dá uma olhada e fazer o merge?

2022-08-13 20:15 UTC, afonsocardz requested changes
Utilizar o contexto de usuário já criado para manipular as informações de autenticação do usuário.

2022-08-13 20:51 UTC, carlosandretaiga reviewed
ok

2022-08-13 21:02 UTC, closed without merging